# fly.toml app configuration file generated for queuesim on 2025-02-28T18:50:29-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'queuesim'
primary_region = 'sea'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'